import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";
import { BE_API_LOCAL, USER_API } from "../config";
import { selectTokens } from "../slices/auth.slice";

// Define a service using a base URL and expected endpoints
export const userAPI = createApi({
  reducerPath: "userManagement",
  // Tag types are used for caching and invalidation.
  tagTypes: ["UserList"],
  baseQuery: fetchBaseQuery({
    baseUrl: BE_API_LOCAL,

    prepareHeaders: (headers, { getState }) => {
        const token = selectTokens(getState());
        if (token) {
          headers.append("Authorization", `Bearer ${token}`);
        }
        headers.append("Content-Type", "application/json");
        return headers;
      },
  }),
  // baseQuery: fetchBaseQuery({ baseUrl: CLASS_API_URL }),
  endpoints: (builder) => ({
    // Supply generics for the return type (in this case `FlowerApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getAllUser: builder.query({
      query: () => `users`,
      providesTags: (result) =>
        result
          ? result.map(({ id }) => ({ type: "UserList", id }))
          : [{ type: "UserList", id: "LIST" }],
    }),
    getUserProfile: builder.query({
      query: (userId) => ({
        url: `user/${userId}`, // Use template literal for security
        method: "GET",
      }),
    }),
    createUser: builder.mutation({
        query: (body) => {
          return {
            method: "POST",
            url: `users`,
            body,
          };
        },
        invalidatesTags: [{ type: "user", id: "LIST" }],
      }),

    // getClassById: builder.query({
    //   query: (classId) => ({
    //     url: `viewclass/${classId}`, // Use template literal for security
    //     method: "GET",
    //   }),
    //   providesTags: (result) => {
    //     if (Array.isArray(result)) {
    //       // Handle array case (multiple classes)
    //       return result.map(({ id }) => ({ type: "ClassList", id }));
    //     } else if (result && result.id) {
    //       // Handle object case (single class)
    //       return [{ type: "ClassList", id: result.id }];
    //     } else {
    //       // Handle no data case (optional)
    //       return [];
    //     }
    //   },
    // }),

    // duplicateClass: builder.mutation({
    //   query: (body) => {
    //     return {
    //       method: "POST",
    //       url: `viewclass`,
    //       body,
    //     };
    //   },
    //   invalidatesTags: [{ type: "ClassList", id: "LIST" }],
    // }),

    // createClass: builder.mutation({
    //   query: (body) => {
    //     return {
    //       method: "POST",
    //       url: `class/create`,
    //       body,
    //     };
    //   },
    //   invalidatesTags: [{ type: "ClassList", id: "LIST" }],
    // }),

    editUser: builder.mutation({
      query: (payload) => {
        return {
          method: "PATCH",
          url: `users/` + payload.id,
          body: payload.body,
        };
      },
      invalidatesTags: (res, err, arg) => [{ type: "user", id: arg.id }],
    }),
    
    deleteUser: builder.mutation({
      query: (payload) => ({
        method: "DELETE",
        url: `users/` + payload,
      }),
      invalidatesTags: [{ type: "UserList", id: "LIST" }],
    }),
  }),
});

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
// Hooks are auto-generated by RTK-Query
export const {
  useGetAllUserQuery,
  useGetUserProfileQuery,
  useCreateUserMutation,
  useEditUserMutation,
  useDeleteUserMutation,
  // useGetAllProductQuery,
  // useGetAllCategoriesQuery,
  // useGetProductDetailQuery
} = userAPI;
